wip

diff --git a/.github/actions/build-test-and-run/action.yml b/.github/actions/build-test-and-run/action.yml
--- a/.github/actions/build-test-and-run/action.yml
+++ b/.github/actions/build-test-and-run/action.yml
@@ -17,3 +17,19 @@ runs:
         cmake --install ./build/${{ inputs.preset }} --config ${{ inputs.build_type }}
       shell: bash
       working-directory: ${{ inputs.nakama-cpp-path }}
+    - id: setup-postgres
+      uses: ikalnytskyi/action-setup-postgres@v3
+      with:
+        username: root
+        database: nakama
+        port: 26257
+    - uses: ./.github/actions/run-nakama
+      with:
+        postgres_uri: "${{ steps.setup-postgres.outputs.connection-uri }}"
+    - shell: bash
+      run: |
+        ./${{ inputs.nakama-cpp-path }}/test/out/${{ inputs.preset }}/nakama-test || {
+            echo "Test failed, showing Nakama log for diagnostics";
+            cat /tmp/nakama.log;
+            exit 1;
+        }
